### ISSUE TITLE
接收处理问题

### ISSUE THREAD

**Issue by GitCP** [Serial-Studio/Serial-Studio#56] opened 2021-04-25 03:07 UTC
在设置好115200 8N1 没有流控制的情况下，接收中文出现乱码

**Comment by alex-spataru** [comment] 2021-04-26 02:31
Hi! If you click on the "export console data" button, do the characters appear as they should on your system's text editor? I want to know if this issue is caused by the data display code or the serial data processing code.

<img width="1279" alt="Screen Shot 2021-04-25 at 9 28 16 PM" src="https://user-images.githubusercontent.com/4225542/116021266-799c3c80-a60d-11eb-9303-51e9b84019ee.png">

Attached to this message is a screenshot with the location of the "export console data" button.

**Comment by alex-spataru** [comment] 2021-09-04 00:58
I'm closing this issue for now to focus on what should be done for the next release. Please let me know if I should re-open this issue :)

**Closed by alex-spataru** 2021-09-04 00:58 UTC
Labels: enhancement
